language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
env:
  global:
  - secure: JGJSxwU7iFSHFjhKmuKRRRzVkp+RTRCvvHWId7NvQ+kzxFEGTEsv+XZ1wO919c9y0W9P4w8hk4MxsKJruYuiXbSzR8Jcy8WEdDsaCdz4lOzjdsvOJ35KQWOHkyP1fSFYpx549PcbtV5PO4LpDVwe8SdNHY+oPGAf18aIeEGALYfp5bwr6kwWtzz0e0d1njK8aAae98YGqOKIEnfOxXBc9qtbSzCgyspec9OFlF1fgmJl5+UqTLs6YVxzFuhjx4G06vIVCA8ZYk7o7EXE0iOqhYHwN/ppRqUDerhedsCWgWqgnx65PXC5wMIXDPUFHsfWpvTRHpP0HmoPuzYXBFaWfNAhByLSL4jvPJ+njVkNOWydxDkaLXxYPx2EPM4Ln9GWHVf7Ct2sWC3ToT/FODIWvz6FtwcLmxXnJnxiT+hy+q0/G1IYlR4QEVYgab2VgAXwisw0BEvGPB5QXLfLP+X3PC95VT0OXEnEmPfBZzj7ZK1ypdLbOLZx28IvZalTFdYr9N2jgTG94pm2DEWZBU1Rj8zGtqDxlmOQ7Okvhjjf2NPehjPI/+3tardGqugahpHL6DPACmNe/BwjglgVrFCrlBjVShBr2CceNQD+el7MQRAGtxKOpEFq7Iymf7g7pd9gHGfEJ3Iel8FHKHBO7Ru8mGkl05l3f1QWM2b8DQiKpQU=
  - secure: DCX+CMPQDOh7wUgamXhLdmHVzd1ZDbLWOueNawVs530wqxEPuKB/JtkDkO1gVvQEXVxD1N6p9qyB7tKcXvIPBIJ2tL0LYu5w+0rioKZXgnWKHY4KXOkNWD4PCvN43XI8y8F8nOc7IyOeCgr2NZb6Eg7gjz4Puyjz4NUDSySSmanhH67BqOqxvq5NtFuXccxeByKFvJHC8scePvZhpRZcnvDns4Ze0srMCzfqdzOlzlou3VgdLD68PIiqu0fFUiqdwX4FzbwUc846CtXMtR2xpWUJQtzf7t7zKdJP5DvVTzdW3geaC+6bn2vihLbG1wE/VOBPkLvD1lwEMy5jtgLtY+Af1bsp0ZEYVDuY89FlD88LXh/4Ymru/EOzRI03CK4qnmTU0q0fCqDjv27vxcPofPeowFAgsaXaCU+5HvHQgEhxkA+AlQiKY/ImvRl0Xc3NyrAXEBMBLMMEkIJYsRWpr8abHI3iVY0PTeyXx63g0BE76fPcX5JaTKnxws51JvOyBdexPAErb56V0TXbCKfzMt7D+/ovMC//YpT2Rh4u4jg8VaqdLErUJe3aEhRkwJJa8a0zwbxn7idcQfalmsqkX4preC/z6SDZA9jgfmakulZK9Vst+ZyxQc549JE3FExETr8LhMMhzKciPTa4A5pytK72dOBSBOzZ4Y4NtZZ2Bv4=
  - secure: XZaVzpewCuHBOMxzp95H0Bue4LHBFmDHxGYoJsUf4I7Yt7zcGD55mHzjdfJRyxg6AOLse2wNCPCh4LKXVFXW+cilCAnUy30VXGNHJGjwYwleqHmtpVDRHXPsdr5CnxVLtseCFi/zTYnXA09vWPdCTMJ+zvd/u2ynAth3Ksp75ATEQgfPGhDUyD9hNCUiJt2KM8NcSgmotS37hMOSpfmNRzCNbITcuz1cpXROlF4CASAHPjsjT+e3LlCA7abpa3DjBfrNINu8dGogl+R1ZHntIeItWERllyLSd/vGJYO7gYr73Hy7yfNJOWgUbmX1Izro3+ghiFK05FosCZHeDu7nOqijVNmW5eoBcjzbh+zR1nljzkCiEaDwZaPBdpuC0QS8pbQcqUvm7qiwmgWRQv+eyGQvgp7Re2o+2UP+pJfdb+QjOUjWGD0gbFV2n05RD3OxEZt1JpGjTPntEmhjQkC5VvTDSXtkRk3t/eppVaODvOwztZRbhbmeUyoNbgujdiDnoDxOAky/aMEQqrbG6mN5/kB5faGd8xHNiI5CibeaZpWUWo5CfR5cLc+KvVS4gfLKtLbW7sNYKtuYe1U66F+ydKZj8sm6cnDouigGnGdCJ74NSX3w31ctRQrLRV19DeH/G24zNc8v3uX4WYgnTvHN4ZYazppogskUmIbOI/E93W8=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_error: always
    on_cancel: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
branches:
  except:
  - /^v?\d+\.\d+\.\d+/
