language: java
install: true
script: bash travis-build.bash
jdk:
- oraclejdk8
env:
  global:
  - secure: P72qy5AbgN9MLnboWyMh8enYcyBdFtR9dMr9QpIJ0fvuasiZWklXT04MiLxRo13FChIlKRP8SXJkl4pkPjbcj5EskZhUlstJldr4rjtDfkRZdrhoT5BQYMAtO1TcEL/az36BJGnXu07129OWTrSpLbttuixGH/xgfiQHIKcAC5jlCvpsZ+30EpCGrsCB6RRt+1QyCjhdIFtyJfE3Iaep+G/VHt7bw5OPDuLYVOCappJM2v3+mDsGftBJSjwjMz/iqe9MMT4sBCDXTR6DVH3mPbzVYmv7gStBVWUQhWpc6cbeUosPk0ARQQv7IVsls7PAxndATxtH/wemUrK4xq8lLezVJTfN/MqgIFPtMw/vpFfiOzjhcIIooAPUwPVX/2BjfEwXSB27JZvuVq3PgAkceWQjkd+glDlsl1b4piLRAVXeGUbWz/eXZC5KEscy3ozAjFXwvPMnQ68xcoNVObhUfS6NMdyGamyi9kNT36U0Qev9Jv6jLdSfjhz30ccQAg0SPBvDm+cwuLOSX+wXOpymrwLphozXZiPBPuqyk9LTP4AQGuZe1UR5riOsFc6yMlcN9aYkSa/KXBE5Nm7G13pLYn6YDat09LcxIO2gY7ra9Gm0cnS0t9GUMbUWjGg6UI3mNcyJF+lO+ekC8goQjQf55YvGbC6pRNUJw5Bd9Y4p4ZU=
  - secure: QcGDsuDuQE9/liUQAy2AgGcUoWJXZMVndzkCNWrVygJbL4KJpBpu/9Ea5EoIrekdIdgCMV50MIf9I0bSuIz5ov0IJkqSkUCM+UmsWs/Eh2n0BWXqiVe6f+Zjm7ZMSUtQlOLuQm0Frg3atxE1XW1mOVOlSBc1eAF4CXGZNOVDI/l4n06lc2ceVZMrl/7UHQwuAET8TFLO94q8my3i4DC+ItSlUvwqZztkKbh4AWK/iT7KXPjzhcvWNcXsbzuJXNwJ5ncN1XjtamGOqlO8UaIcrbQFrkUgtKos1v2JJuXvyS4e+slP4jDVYy0rCNn4rEEvY3ARAq5vhkbbiEygOoRux0oS+BVdycenTlJoS4js/K6kqVTXu2dCp+ZIzpzoseNvuy1s6OD8mdgRLuGeaJXaYT9/00wwOn3I3c0sVkTm24UGu9XQFyeJyCF318TAGNmzhTYGYOIBRoeKUvmU9lqP/nTX6VU2vhMrYcE+cN3rIW5NzbuncCckM44RYicOeNR2ZY20yjqYySAy1dVKtRsgRp1yjOS+rNMFi92qQZDClLocKJOWEnmlb8a+mEGzNqt+0i5uVevExnzkmwsXRsgA0np/AUmvZ29GbfpExd6bBxk7zHzg+DL5EHwG1tGdZ1r4D4DnovNx0QFsqzfhd0RcOtqrxWk0sDC9o8FnA0l+lek=
  - secure: Vyd8OitFD4baVBPmuEcfjNitT2Y3hbpenLg+nXx3JOuCVK8owdF0xK1QVRvPLTRaJmX/mU0YEBFsKdhUw5kpxe1Ag/DsA5/ek9eKQeWJX10CDKquVB7mPDCGoYe7opmxoUX7GjT4V54MwQrqoICrvm3PBw1ej0IlQaeuFC/KBcyKM6bukWzqxsTZFredz0e1Gfae/tbCT1gySfsa73R8WWc6dDWVsjYDn3QeeAVdStyxsAgQPLrzShUyYu/714gMpM/pwe1B0faiW+CRwewBLYsTmVVawxcawWKgb6+Z/8c9hxndnyta6wEq9B7K9gBnL2Gw6FnLsa6P4sSspILUEwUaDfstAq002mdQc5yWmaMokaY+h+oYQNgH3I+f6FRK0cv6xP4eJlm2yRtS6utf7utO7W31QnqWbrQtobosbFeRFUbxOwE6vi+zPxpK3faQ9de5FULUEy8dfr08m6klmH9AZm1Fkds4AxrNWHRu5vD7SyGRo5Wd9nBYOXkwhLyguLklxfE7TxMpgzV7l4Qq74nq1Ha/FlnTU02/WLTKrLHLAo459zjvcXlZYFFkMKR12eaoTV/yxLio5ZdQ+cnldNkAkFGZGIu+h0dKe341ZWsc8Ly5pRkcx594tXJY+Yb/yOw7ZcK9VJFEfyjnlSLAtpW7Gs1EjPKCY3xU3pXlWtA=
notifications:
  email: false
  webhooks:
    on_success: always
    on_failure: always
    on_start: always
    on_error: always
    on_cancel: always
    urls:
    - https://webhook.atomist.com/travis
cache:
  directories:
  - $HOME/.m2
branches:
  except:
  - /^v?\d+\.\d+\.\d+/
